### PR TITLE
Support the optional use of Jokers in the pack

### PR DESCRIPTION
**Pull request by andrewjt71**
**Summary**
I thought it would be a nice feature to support the use of jokers in the pack. As the majority of games do not require Jokers, the default is for Jokers to be excluded from the pack. However, should someone wish to include Jokers in the pack, they can do so by adding the query parameter `?jokers=1`.

**Joker image**
I found the [joker image](https://publicdomainvectors.org/en/free-clipart/Harlequin-vector-clip-art/73917.html) on [publicdomainvectors.org](https://publicdomainvectors.org/). I used one of your [other card images](https://deckofcardsapi.com/static/img/JC.png) as a base template to get the dimensions right and added some "Joker" text.

Hope you like this feature, feedback is welcomed!

### CODE REVIEW

**Comment by andrewjt71** [comment]
Update: resolved conflicts caused by https://github.com/crobertsbmw/deckofcards/pull/60 merge 🙂

**Comment by crobertsbmw** [comment]
Thanks for this! 
I made some edits and merged this in. Hopefully I didn't break everything.
I didn't like using "??" as the card code for the joker so I changed it "xx". I thought using question marks might screw up get requests or something.
I also thought it would be a little cleaner to just have a seperate array with `JOKERS = ["XX", "XX"]` instead of two arrays `CARDS_EXCLUDING_JOKERS` and `CARDS_INCLUDING_JOKERS`. I made some other small tweaks and rewrote the updates to the docs as well. 
Thanks again!

**Comment by andrewjt71** [comment]
Hey @crobertsbmw you're welcome, glad you like the feature!

Yeah agree with the naming of the Jokers, XX is definitely more fitting.

One line I'm not sure about is this line: https://github.com/crobertsbmw/deckofcards/commit/5616cd194a0494c1f1dad74f8eb22410b0cd0015#diff-c4f42f554231c4bced5721ef2475c1feR55. My understanding is that `CARDS` here will exclude Jokers, but we should be including them here if Jokers are enabled?

**Comment by crobertsbmw** [comment]
So that line is when someone requests a partial deck by specifying which cards to include. When I tested it with jokers included and enabled I tried doing 
`http://127.0.0.1:8000/api/deck/new/shuffle/?jokers=1&cards=AS,2S,3S,JK`
The problem is that the code for jokers isn't unique so it included two jokers when I was expecting only one. Rather then assign the jokers different card codes, I figured if someone is using a partial deck, then they probably don't have to use jokers, so I essentially made Jokers only available for full decks.

**Comment by andrewjt71** [comment]
Hi @crobertsbmw, sure I see your logic now. Another approach could be to assign different values to each, both which are matched to the 'Joker' value, but I think the assumption that if someone is using a partial deck then they will likely not wish to include jokers is fair.

However, I have noticed a bug that your changes have introduced. In the following line you are assigning a new variable which points (by reference) to the existing `CARDS` array. This is causing the more and more Jokers to be added to the pack (for all users) each time the code is run:

https://github.com/crobertsbmw/deckofcards/commit/5616cd194a0494c1f1dad74f8eb22410b0cd0015#diff-c4f42f554231c4bced5721ef2475c1feR49

Replication steps:
Hit https://deckofcardsapi.com/api/deck/new/shuffle/?deck_count=1, there are currently 64 cards being returned

**Comment by andrewjt71** [comment]
Hey @crobertsbmw, have addressed the above in the following PR: https://github.com/crobertsbmw/deckofcards/pull/62. This adds a few enhancements, and also resolves the live issue caused by https://github.com/crobertsbmw/deckofcards/commit/5616cd194a0494c1f1dad74f8eb22410b0cd0015#diff-c4f42f554231c4bced5721ef2475c1feR49 and https://github.com/crobertsbmw/deckofcards/commit/5616cd194a0494c1f1dad74f8eb22410b0cd0015#diff-2b76ae8a9f26a6ef7c47144b4782de6dR136. Hope this helps! Let me know if you need a hand.

Thanks!
Andrew

**Comment by crobertsbmw** [comment]
Okay, now I see. Sorry, I saw the PR before seeing this comment. Thanks
again for helping get this sorted out.

Best,
Chase

**Comment by andrewjt71** [comment]
No problem at all, happy to contribute!

Thanks,
Andrew

**Pull request merged**
